baseURL: http://ruckgaber.pl/
languageCode: en-GB
title: Jean Ruckgaber
themesDir: themes
theme: hyde

params:
  description: Forgotten composer
Menus:
  main:
    - Name: Life
      url: /en/life
    - Name: Work
      url: /en/work
    - Name: About
      url: en/about
